FROM ubuntu:24.04

ENV TZ Asia/Tokyo
ARG UID
ARG GID
ARG PROJECT
ARG USERNAME=neovim

RUN apt-get update && apt-get install -y curl git sudo \
    language-pack-ja-base language-pack-ja \
    ca-certificates tmux make gcc ripgrep unzip && \
    # nvim install 
    curl -LO https://github.com/neovim/neovim/releases/download/stable/nvim-linux-x86_64.appimage && \
    chmod u+x nvim-linux-x86_64.appimage && \
    ./nvim-linux-x86_64.appimage --appimage-extract && \
    ./squashfs-root/AppRun --version && \
    ln -s /squashfs-root/AppRun /usr/bin/nvim && \
    rm nvim-linux-x86_64.appimage 

# In case Python and poetry
# RUN apt-get install -y python3 python3-venv && \
    # curl -sSL https://install.python-poetry.org | python3 - && \
    # ln -s /opt/poetry/bin/poetry /usr/local/bin/python-poetry

# In case uv
ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && rm /uv-installer.sh
# ENV PATH="/root/.local/bin:${PATH}" # same path is set in setting Aider

# setup user
RUN userdel -r ubuntu && \
    groupadd -g ${GID} ${USERNAME} && \
    useradd -u ${UID} -g ${GID} -s /bin/bash -m ${USERNAME} && \ 
    echo "${USERNAME} ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers

# basic env variables for Aider
ENV AIDER_MODEL="sonnet"
ENV AIDER_EDIT_FORMAT="diff"
ENV AIDER_AUTO_COMMITS="false"
# ANTHROPIC_API_KEY should be set through .env

# install Aider
RUN curl -LsSf https://aider.chat/install.sh | sh && \
    chmod -R +rx /root
ENV PATH="/root/.local/bin:${PATH}"

# git auto-completion
RUN curl -o /home/${USERNAME}/.git-completion.bash https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash && \
    echo "source ~/.git-completion.bash" >> /home/${USERNAME}/.bashrc

# setup neovim
COPY --chown=${USERNAME} dotfiles/.config/nvim/init.lua /home/${USERNAME}/.config/nvim/init.lua
COPY --chown=${USERNAME} dotfiles/.config/nvim/lua/plugins/default.lua /home/${USERNAME}/.config/nvim/lua/plugins/default.lua
COPY --chown=${USERNAME} dotfiles/.config/nvim/lua/plugins/Python.lua /home/${USERNAME}/.config/nvim/lua/plugins/Python.lua
COPY --chown=${USERNAME} dotfiles/.config/nvim/lua/custom/Python.lua /home/${USERNAME}/.config/nvim/lua/custom/Python.lua
COPY --chown=${USERNAME} dotfiles/.tmux.conf /home/${USERNAME}/.tmux.conf
COPY --chown=${USERNAME} dotfiles/.aiderignore /home/${USERNAME}/.aiderignore
RUN echo "alias tmux='tmux -u'" >> /home/${USERNAME}/.bashrc && \
    echo "require('custom.Python')" >> /home/${USERNAME}/.config/nvim/init.lua

USER ${USERNAME}
WORKDIR /workspaces/${PROJECT}/

RUN nvim --headless "+Lazy! sync" +qa

